#
#
#
all:

build:


install:
	bun link
	sudo cp index.js /usr/local/include/testme.js
	sudo mkdir -p /usr/local/lib/testme
	sudo cp package.json /usr/local/lib/testme
	sudo cp index.js /usr/local/lib/testme
